version: "3"
services:
  my-nextjs-app:
    image: saashqdev/saashq:0.0.3-beta
    container_name: saashq
    ports:
      - "3001:3000"
    volumes:
      - .env:/app/.env
      - .env.local:/app/.env.local